server:
  port: 7008
  
spring:
  application:
    name: config  #应用名称
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka  
#,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    #服务实例名称修改
    instance-id: config-client
    #访问路径显示IP地址
    prefer-ip-address: true
    
    
#rabbitmq:#本地环境不需要配置mq
   #host: localhost
   #port: 5672
   #username: user
   #password: 123456

security:                                #
  basic:
    enabled: false

